kind: pipeline
name: Build
type: docker

steps:
  - name: Restore Cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: Install Dependancies
    pull: if-not-exists
    image: node:lts-bullseye-slim
    commands:
      - yarn install --frozen-lockfile
  - name: Build
    pull: if-not-exists
    image: node:lts-bullseye-slim
    commands:
      - yarn build
  - name: Publish Github Pages
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: build/
  - name: Rebuild Cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache
